export const contentProjects: ProjectTypes.Content[] = [
	{
		id: 0,
		footer: true,
		title: 'KBDev Website',
		desc: 'KBDEV',
		link: 'https://kbdev.io',
		techs: [
			'next',
			'react',
			'typescript',
			'sass',
			'nodeMailer',
			'affinityDesigner',
			'framerMotion',
		],
		screens: [
			'kbdevAulia',
			'kbdevAuliaMobile',
			'kbdevDigitalSupport',
			'kbdevHome',
			'kbdevHomeMobile',
		],
	},
	{
		id: 1,
		footer: true,
		title: 'Petshine',
		desc: 'PETSHINE',
		link: 'https://www.petshine.dubj.fr',
		techs: ['next', 'react', 'typescript', 'sass', 'figma'],
		screens: [
			'petshineCarousel',
			'petshineFav',
			'petshineHome',
			'petshineHomeMobile',
			'petshineNav',
			'petshineWelness',
		],
	},
	{
		id: 2,
		footer: false,
		title: 'TCG-Collect',
		desc: 'TCG',
		techs: [
			'typeOrm',
			'postgreSql',
			'express',
			'reactNative',
			'typescript',
			'sass',
			'figma',
		],
		screens: [
			'tcgBackCard',
			'tcgCards',
			'tcgFilters',
			'tcgProfil',
			'tcgSeries',
		],
	},
];
